accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path('', views.article_list, name="list"),
    path('create/', views.article_create, name="create"),
    path('<slug>/', views.article_detail, name="detail"),
    path('<slug>/comment/', views.article_comment, name="comment"),
    path('<slug>/like/', views.article_like, name="like"),
]

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf.urls.static import static
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('', article_views.article_list, name="home" )
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumbnail = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def snippet(self):
        if len(self.body) > 100:
            return self.body[:100] + " ..."
        else:
            return self.body

class Comment(models.Model):
    article = models.ForeignKey('articles.Article', on_delete=models.CASCADE, related_name='comments')
    text = models.CharField(max_length=100)
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.text
    
class Like(models.Model):
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)    
    article = models.ForeignKey('articles.Article', on_delete=models.CASCADE, related_name='likes')
    date = models.DateTimeField(auto_now_add=True)

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = [
            "title",
            "body",
            "slug",
            "thumbnail"
        ]

class CreateComment(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = [
            "text",
        ]
        

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form':form})

def login_view(request):
    if request.method =="POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if "next" in request.POST:
                return redirect(request.POST.get("next"))
            return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render, redirect
from .models import Article, Like
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html', {'articles' : articles})

def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article' : article})

@login_required(login_url="/accounts/login")
def article_create(request):
    if request.method == "POST":
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # Get the author, but not saving it just yet
            instance = form.save(commit=False)
            instance.author = request.user
            # Now save it for real
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'form':form})

@login_required(login_url="/accounts/login")
def article_comment(request, slug):
    article = Article.objects.get(slug=slug)
    if request.method == "POST":
        form = forms.CreateComment(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.article = article
            instance.save()
            return redirect('articles:detail', slug=slug)
    else:
        form = forms.CreateComment()
    return render(request, 'articles/article_comment_create.html', {'form': form, 'article':article})

@login_required(login_url="/accounts/login")
def article_like(request, slug):
    article = Article.objects.get(slug=slug)
    if request.method == "POST":
        new_like, created = Like.objects.get_or_create(author=request.user, article=article)
        if created:
            new_like.save()   
            return redirect('articles:detail', slug=slug)
    return redirect(request.META['HTTP_REFERER'])

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content%}
    <h1>Log In</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        {{ form  }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit" value="Log In">
    </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content%}
    <h1>Sign Up</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="POST">
        {% csrf_token %}
        {{ form  }}
        <input type="submit" value="Sign Up">
    </form>
{% endblock %}

articles/templates/articles/article_comment_create.html
{% extends 'base_layout.html' %}

{% block content%}
    <div class="create-comment">
        <h2>Write Your Comment Here!</h2>
        <form class="site-form" action="{% url 'articles:comment' slug=article.slug %}" method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content%}
    <div class="create-article">
        <h2>Create An Awesome New Article!</h2>
        <form class="site-form" action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
    <script src="/static/slugify.js"></script>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content%}
    <div class="article_detail">
        <div class="article">
            <img src="{{article.thumbnail.url}}"/>
            <h2>{{ article.title }}</h2>
            <h6>{{ article.likes.all.count }} Likes</h6>
            <h6>{{ article.comments.all.count }} Comments</h6>
            <p>{{ article.body }}</p>
            <p>{{ article.date }}</p>
            <form id="likebutton" action="{% url 'articles:like' slug=article.slug%}" method="POST">
                {% csrf_token %}
                <button type="submit" value="Like">Like It!</button>
            </form>
            <a class="button" href="{% url 'articles:comment' slug=article.slug %}">Add new comment: </a>
            {% for comment in article.comments.all %}
                <div class="comment">
                    <strong>{{ comment.author }}</strong>
                    <p>{{ comment.text|linebreaks }}</p>
                    <p>{{ comment.date }}</p>
                </div>
            {% empty %}
                <p>No comments here yet :(</p>
            {% endfor %}
        </div>
    </div>
    
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content%}
    <h1>Article List</h1>
    <div class="articles">
        {% for article in articles %}
            <div class="article">
                <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
                <h6>{{ article.likes.all.count }} Likes</h6>
                <h6>{{ article.comments.all.count }} Comments</h6>
                <p>{{ article.snippet }}</p>     
                <p>{{ article.date }}</p>     
                <p class="author">added by: {{ article.author.username }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Articles</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>

<body>
    <div class="wrapper">
        <nav>
            <a href="{% url 'home' %}"><img src="{% static 'logo.png' %}" alt="logo" height="42" width="42"/></a>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="POST">
                        {% csrf_token %}
                        <button type="submit">Log Out</button>
                    </form>
                </li>
                <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
                <li>Hello, {{ user.username }}</li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}">Log In</a></li>
                <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
                {% endif %}
            </ul>
        </nav>
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>